# Site
name: "안성논수저 블로그"
title: "안성논수저 블로그"
description: "안성논수저 블로그의 메인 화면입니다! 반갑습니다!"
logo: 'assets/images/dlatl.png'
favicon: 'assets/images/dlatl.png'
baseurl: ""
url: "https://yujinyeom.github.io/"
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: yujinyeom@shinsegae.com

# Authors
authors:
  yujin:
    name: yujin
    display_name: yujin
    avatar: 'assets/images/yujin.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81 #??뭐징
    email: yujinyeom@shinsegae
    web: https://yujinyeom.github.io
    twitter: https://twitter.com/
    description: "염유진입니다. 반가워요"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
